city
department
intervention_type
intervention
illness_type
illness
address
patient
hospital
staff
profession
staff_profession
patient_lifestyle
patient_indicator
appointment
staff_appointment
appointent_results
patient_illness (from trigger)
patient_recreational_usage
recreation
hospital_department
illness_types
appointment_symptom
appointment_result_finding
finding
symptom
stock_type
hospital_stock
stock
appointment_stock
HOSPITALIZED - NEEDED
HOSPITALIZATION_CAUSE - NEEDED
SHIFT - NEEDED
FEEDBACK - NEEDED
STAFF_PERFORMANCE - NEEDED
